import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { map, Observable, of } from 'rxjs';
import { JudetOrase } from '../interfaces/JudetOrase';

@Injectable({
  providedIn: 'root',
})
export class JudeteService {
  constructor(private http: HttpClient) {}

  private judeteOrase: JudetOrase = {
    Alba: [
      'Alba Iulia',
      'Aiud',
      'Blaj',
      'Cugir',
      'Sebeș',
      'Ocna Mureș',
      'Zlatna',
      'Abrud',
      'Teiuș',
      'Baia de Arieș',
    ],
    Arad: [
      'Arad',
      'Chișineu-Criș',
      'Curtici',
      'Ineu',
      'Lipova',
      'Nădlac',
      'Pâncota',
      'Pecica',
      'Sântana',
      'Sebiș',
    ],
    Argeș: [
      'Pitești',
      'Câmpulung',
      'Curtea de Argeș',
      'Mioveni',
      'Costești',
      'Topoloveni',
      'Ștefănești',
      'Bascov',
    ],
    Bacău: [
      'Bacău',
      'Onești',
      'Moinești',
      'Comănești',
      'Dărmănești',
      'Târgu Ocna',
      'Slănic-Moldova',
      'Buhuși',
    ],
    Bihor: [
      'Oradea',
      'Beiuș',
      'Marghita',
      'Salonta',
      'Aleșd',
      'Valea lui Mihai',
      'Ștei',
      'Vadu Crișului',
      'Săcueni',
    ],
    'Bistrița-Năsăud': ['Bistrița', 'Beclean', 'Năsăud', 'Sângeorz-Băi'],
    Botoșani: [
      'Botoșani',
      'Dorohoi',
      'Darabani',
      'Săveni',
      'Flămânzi',
      'Bucecea',
    ],
    Brașov: [
      'Brașov',
      'Făgăraș',
      'Săcele',
      'Codlea',
      'Râșnov',
      'Zărnești',
      'Predeal',
      'Victoria',
      'Ghimbav',
    ],
    Brăila: ['Brăila', 'Ianca', 'Însurăței', 'Făurei'],
    Buzău: ['Buzău', 'Râmnicu Sărat', 'Nehoiu', 'Pătârlagele', 'Pogoanele'],
    'Caraș-Severin': [
      'Reșița',
      'Caransebeș',
      'Bocșa',
      'Moldova Nouă',
      'Oravița',
      'Oțelu Roșu',
      'Anina',
      'Băile Herculane',
    ],
    Călărași: ['Călărași', 'Oltenița', 'Budești', 'Fundulea', 'Lehliu Gară'],
    Cluj: ['Cluj-Napoca', 'Turda', 'Dej', 'Câmpia Turzii', 'Gherla', 'Huedin'],
    Constanța: [
      'Constanța',
      'Mangalia',
      'Medgidia',
      'Năvodari',
      'Cernavodă',
      'Eforie',
      'Ovidiu',
      'Hârșova',
      'Techirghiol',
    ],
    Covasna: [
      'Sfântu Gheorghe',
      'Târgu Secuiesc',
      'Covasna',
      'Baraolt',
      'Întorsura Buzăului',
    ],
    Dâmbovița: [
      'Târgoviște',
      'Moreni',
      'Pucioasa',
      'Găești',
      'Titu',
      'Fieni',
      'Răcari',
    ],
    Dolj: [
      'Craiova',
      'Băilești',
      'Calafat',
      'Filiași',
      'Segarcea',
      'Dăbuleni',
      'Bechet',
    ],
    Galați: ['Galați', 'Tecuci', 'Târgu Bujor', 'Berești'],
    Giurgiu: ['Giurgiu', 'Bolintin-Vale', 'Mihăilești'],
    Gorj: [
      'Târgu Jiu',
      'Motru',
      'Rovinari',
      'Târgu Cărbunești',
      'Bumbești-Jiu',
      'Novaci',
      'Tismana',
      'Turceni',
    ],
    Harghita: [
      'Miercurea Ciuc',
      'Odorheiu Secuiesc',
      'Gheorgheni',
      'Toplița',
      'Cristuru Secuiesc',
      'Vlăhița',
      'Bălan',
      'Borsec',
    ],
    Hunedoara: [
      'Deva',
      'Hunedoara',
      'Petroșani',
      'Vulcan',
      'Lupeni',
      'Brad',
      'Orăștie',
      'Simeria',
      'Uricani',
      'Hațeg',
    ],
    Ialomița: ['Slobozia', 'Fetești', 'Urziceni', 'Țăndărei', 'Amara'],
    Iași: ['Iași', 'Pașcani', 'Târgu Frumos', 'Hârlău', 'Podu Iloaiei'],
    Ilfov: [
      'Voluntari',
      'Pantelimon',
      'Buftea',
      'Popești-Leordeni',
      'Otopeni',
      'Măgurele',
      'Chitila',
      'Bragadiru',
    ],
    Maramureș: [
      'Baia Mare',
      'Sighetu Marmației',
      'Borșa',
      'Vișeu de Sus',
      'Târgu Lăpuș',
      'Seini',
      'Baia Sprie',
      'Cavnic',
    ],
    Mehedinți: [
      'Drobeta-Turnu Severin',
      'Orșova',
      'Strehaia',
      'Baia de Aramă',
      'Vânju Mare',
    ],
    Mureș: [
      'Târgu Mureș',
      'Reghin',
      'Sighișoara',
      'Târnăveni',
      'Luduș',
      'Iernut',
      'Sovata',
      'Sărmașu',
    ],
    Neamț: ['Piatra Neamț', 'Roman', 'Târgu Neamț', 'Roznov', 'Bicaz'],
    Olt: [
      'Slatina',
      'Caracal',
      'Balș',
      'Corabia',
      'Drăgănești-Olt',
      'Piatra-Olt',
      'Potcoava',
      'Scornicești',
    ],
    Prahova: [
      'Ploiești',
      'Câmpina',
      'Breaza',
      'Comarnic',
      'Sinaia',
      'Bușteni',
      'Mizil',
      'Boldești-Scăeni',
    ],
    Sălaj: ['Zalău', 'Șimleu Silvaniei', 'Jibou', 'Cehu Silvaniei'],
    'Satu Mare': [
      'Satu Mare',
      'Carei',
      'Negrești-Oaș',
      'Tășnad',
      'Livada',
      'Ardud',
    ],
    Sibiu: [
      'Sibiu',
      'Mediaș',
      'Cisnădie',
      'Avrig',
      'Agnita',
      'Dumbrăveni',
      'Tălmaciu',
      'Copșa Mică',
    ],
    Suceava: [
      'Suceava',
      'Fălticeni',
      'Rădăuți',
      'Câmpulung Moldovenesc',
      'Vatra Dornei',
      'Gura Humorului',
      'Vicovu de Sus',
    ],
    Teleorman: [
      'Alexandria',
      'Turnu Măgurele',
      'Roșiorii de Vede',
      'Zimnicea',
      'Videle',
    ],
    Timiș: [
      'Timișoara',
      'Lugoj',
      'Sânnicolau Mare',
      'Jimbolia',
      'Recaș',
      'Buziaș',
      'Făget',
      'Deta',
    ],
    Tulcea: ['Tulcea', 'Măcin', 'Babadag', 'Isaccea', 'Sulina'],
    Vaslui: ['Vaslui', 'Bârlad', 'Huși', 'Negrești', 'Murgeni'],
    Vâlcea: [
      'Râmnicu Vâlcea',
      'Drăgășani',
      'Băile Olănești',
      'Băile Govora',
      'Călimănești',
      'Horezu',
      'Brezoi',
    ],
    Vrancea: ['Focșani', 'Adjud', 'Panciu', 'Odobești', 'Mărășești'],
  };

  getJudețe(): Observable<string[]> {
    return of(Object.keys(this.judeteOrase));
  }

  getOraseByJudet(judet: string): Observable<string[]> {
    const orase = this.judeteOrase[judet];
    if (orase) {
      return of(orase);
    } else {
      return of([]);
    }
  }
}
